version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building frontend...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'  # Adjust this if you're using React or similar and have a build folder
